### ISSUE TITLE
Remove this (?)

### ISSUE THREAD

**Issue by ecumene** [parrottjrs/think-write#16]
https://github.com/parrottjrs/think-write/blob/a0660efd4dbf285a4ccead7cbbce469327601175/src/pages/Save.tsx#L40C5-L40C13

**Comment by parrottjrs** [comment]
left in for now until I figure out what I want to do with lock button. Maybe create a dialogue box. "Are you sure you want to lock? Once locked, this note cannot be accessed until lock date has passed." Yes/No. 

If yes:

Type "lock" to lock note, then click return to home. If you have changed your mind, leave field empty before clicking.

**Comment by ecumene** [comment]
## Disregard:

- [ ] Create a generic dialog component
- [ ] Create a specific dialog component for deleting

1. Prompts for typing the word "delete"
2. If spelled correctly, the delete button becomes clickable
3. Clicking delete calls a callback

Checkout this from [RadixUI](https://www.radix-ui.com/docs/primitives/components/dialog) for a dialog primitive (something you can use to create a dialog)
Checkout this from [ShadCN](https://ui.shadcn.com/docs/components/dialog) for styling it

**Comment by ecumene** [comment]
- [x] Move these 3 lines into the handleClick listener

Once you do that, it'll be more clear that this isn't coming from state and is instead coming from localstorage

https://github.com/parrottjrs/think-write/blob/4abbaad2704e154969f3f61bbd83f9e7fdd04135/src/pages/Save.tsx#L10
